spring:
  application:
    name: springboot-ollama

  ai:
    model:
      chat: ollama
    ollama:
      chat:
        model: llama3.2

  logging:
    pattern:
      console: "%green(%d{HH:mm:ss.SSS}) %highlight(%-5level) %magenta([%thread]) %cyan(%logger{20}) - %msg%n"
